defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

title: Your Name
subtitle: Your Site Title

# theme: panthera-jekyll
remote_theme: christianezeani/panthera-jekyll

# Side Menu Links
menu:
  - text: Home
    link: /index.html
    icon: ""

  - text: About
    link: /about.html
    icon: ""

  - text: Fablab Safety
    link: /docs/safety.html
    icon: ""

  - text: Final Project
    link: /docs/project.html
    icon: ""

  - text: Contact
    link: /contact.html
    icon: ""

    # Socialmedia Icons
social_icons:
  - name: linkedin
    link: https://www.linkedin.com/christianezeani
    icon: fab fa-linkedin

  - name: github
    link: https://github.com/christianezeani
    icon: fab fa-github-square

  - name: facebook
    link: https://www.facebook.com/christian.ezeani.cyb
    icon: fab fa-facebook-square

  - name: twitter
    link: https://www.twitter.com/christianezeani
    icon: fab fa-twitter


    
