defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

title: Your Name
subtitle: Your Site Title

# Side Menu Links
menu:
  - text: Home
    link: /
    icon: ""

  - text: About
    link: /
    icon: ""

  - text: Fablab Safety
    link: /docs/safety.md
    icon: ""

  - text: Final Project
    link: /docs/project.md
    icon: ""

# Socialmedia Icons
social_icons:
  - name: linkedin
    link: https://www.linkedin.com/christianezeani
    icon: fab fa-linkedin

  - name: github
    link: https://github.com/christianezeani
    icon: fab fa-github-square

  - name: facebook
    link: https://www.facebook.com/christian.ezeani.cyb
    icon: fab fa-facebook-square

  - name: twitter
    link: https://www.twitter.com/christianezeani
    icon: fab fa-twitter


    
